//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RingCentralDataIntegration
{
    using System;
    using System.Collections.Generic;
    
    public partial class Alias
    {
        public int AliasID { get; set; }
        public string Alias1 { get; set; }
        public int AliasTypeID { get; set; }
        public System.DateTime AliasDate { get; set; }
        public int AliasOrder { get; set; }
        public int StoreID { get; set; }
    
        public virtual AliasType AliasType { get; set; }
        public virtual Store Store { get; set; }
    }
}
