//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RingCentralDataIntegration
{
    using System;
    using System.Collections.Generic;
    
    public partial class Calendar
    {
        public System.DateTime Date { get; set; }
        public string DayName { get; set; }
        public Nullable<int> WeekDay { get; set; }
        public Nullable<int> Week { get; set; }
        public Nullable<System.DateTime> WeekStart { get; set; }
        public Nullable<System.DateTime> WeekFinish { get; set; }
        public string WeekRange { get; set; }
        public string WeekRangeShort { get; set; }
        public Nullable<int> MonthWeek { get; set; }
        public Nullable<int> MonthDay { get; set; }
        public Nullable<int> DaysInMonth { get; set; }
        public Nullable<int> DaysLeftInMonth { get; set; }
        public Nullable<int> Month { get; set; }
        public string MonthName { get; set; }
        public string MonthNameAbbr { get; set; }
        public string MonthYear { get; set; }
        public Nullable<int> Quarter { get; set; }
        public string QuarterName { get; set; }
        public Nullable<int> QuarterWeek { get; set; }
        public Nullable<int> QuarterDay { get; set; }
        public Nullable<int> Year { get; set; }
        public Nullable<int> YearDay { get; set; }
        public Nullable<int> WeekRank { get; set; }
        public Nullable<int> MonthRank { get; set; }
        public Nullable<int> QuarterRank { get; set; }
        public int CalendarTypeID { get; set; }
    
        public virtual CalendarType CalendarType { get; set; }
    }
}
