//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RingCentralDataIntegration
{
    using System;
    using System.Collections.Generic;
    
    public partial class CarrierMetric
    {
        public long MetricID { get; set; }
        public string MetricType { get; set; }
        public string MetricDescription { get; set; }
        public double MetricValue { get; set; }
        public System.DateTime Date { get; set; }
        public string DealerCode { get; set; }
        public Nullable<int> DealerCodeID { get; set; }
        public Nullable<int> StoreID { get; set; }
        public string CarrierMetricType { get; set; }
    }
}
