//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RingCentralDataIntegration
{
    using System;
    using System.Collections.Generic;
    
    public partial class CarrierDealerCode
    {
        public int DealerCodeID { get; set; }
        public string DealerCode { get; set; }
        public Nullable<int> StoreID { get; set; }
        public int AcctStoreID { get; set; }
        public string DealerCodeType { get; set; }
        public string DealerCodeStatus { get; set; }
    }
}
