//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RingCentralDataIntegration
{
    using System;
    using System.Collections.Generic;
    
    public partial class CostCenter
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CostCenter()
        {
            this.GLAccountDetails = new HashSet<GLAccountDetail>();
        }
    
        public int CostCenterID { get; set; }
        public Nullable<int> StoreID { get; set; }
        public Nullable<int> HierarchyNameID { get; set; }
        public Nullable<int> HierarchyLevelID { get; set; }
        public string CostCenter1 { get; set; }
        public Nullable<int> ParentID { get; set; }
        public Nullable<int> AccountLevelID { get; set; }
        public int DivisionID { get; set; }
    
        public virtual Division Division { get; set; }
        public virtual HierarchyLevel HierarchyLevel { get; set; }
        public virtual HierarchyName HierarchyName { get; set; }
        public virtual AccountLevel AccountLevel { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GLAccountDetail> GLAccountDetails { get; set; }
    }
}
