//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RingCentralDataIntegration
{
    using System;
    using System.Collections.Generic;
    
    public partial class DailyPayByStore
    {
        public int StoreID { get; set; }
        public System.DateTime Date { get; set; }
        public string PayGroup { get; set; }
        public Nullable<decimal> Pay { get; set; }
    }
}
