//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RingCentralDataIntegration
{
    using System;
    using System.Collections.Generic;
    
    public partial class DealerHierarchy
    {
        public int DealerHierarchyID { get; set; }
        public int DealerCodeID { get; set; }
        public int DealerHierarchyNameID { get; set; }
        public int DealerHierarchyLevelID { get; set; }
        public Nullable<int> DealerHierarchyParentNameID { get; set; }
        public System.DateTime DealerHierarchyDate { get; set; }
    
        public virtual DealerCode DealerCode { get; set; }
        public virtual DealerHierarchyLevel DealerHierarchyLevel { get; set; }
        public virtual DealerHierarchyName DealerHierarchyName { get; set; }
    }
}
