//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RingCentralDataIntegration
{
    using System;
    using System.Collections.Generic;
    
    public partial class DealerCode
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DealerCode()
        {
            this.DealerCodeCharacteristics = new HashSet<DealerCodeCharacteristic>();
            this.DealerHierarchies = new HashSet<DealerHierarchy>();
            this.Metrics = new HashSet<Metric>();
        }
    
        public int DealerCodeID { get; set; }
        public string DealerCode1 { get; set; }
        public Nullable<System.DateTime> CloseDate { get; set; }
        public Nullable<int> StoreID { get; set; }
        public int AcctStoreID { get; set; }
        public int DealerCodeTypeID { get; set; }
        public Nullable<int> AcquisitionOriginID { get; set; }
        public string DealerCodeOrigin { get; set; }
        public string StoreOriginType { get; set; }
        public int DealerCodeStatusID { get; set; }
        public Nullable<int> DealerCodeOrder { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DealerCodeCharacteristic> DealerCodeCharacteristics { get; set; }
        public virtual DealerCodeStatu DealerCodeStatu { get; set; }
        public virtual DealerCodeType DealerCodeType { get; set; }
        public virtual Origin Origin { get; set; }
        public virtual Store Store { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DealerHierarchy> DealerHierarchies { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Metric> Metrics { get; set; }
    }
}
