//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RingCentralDataIntegration
{
    using System;
    using System.Collections.Generic;
    
    public partial class DefinitionHierarchy
    {
        public int DefinitionHierarchyID { get; set; }
        public int ParentDefinitionID { get; set; }
        public int ChildDefinitionID { get; set; }
        public int CollectionID { get; set; }
        public System.DateTime CreateDate { get; set; }
    
        public virtual Collection Collection { get; set; }
        public virtual Definition Definition { get; set; }
        public virtual Definition Definition1 { get; set; }
    }
}
