//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RingCentralDataIntegration
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmployeeCharacteristic
    {
        public int EmployeeCharacteristicsID { get; set; }
        public int EmployeeID { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public int EmployeeCharacteristicTypeID { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
    
        public virtual Employee Employee { get; set; }
        public virtual EmployeeCharacteristicType EmployeeCharacteristicType { get; set; }
    }
}
