//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RingCentralDataIntegration
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmployeeAdjustment
    {
        public int EmployeeAdjustmentID { get; set; }
        public Nullable<int> EmployeeID { get; set; }
        public int StoreID { get; set; }
        public decimal Adjustment { get; set; }
        public int AdjustmentTypeID { get; set; }
        public System.DateTime AdjustmentDate { get; set; }
        public System.DateTime CreatedDate { get; set; }
    
        public virtual AdjustmentType AdjustmentType { get; set; }
        public virtual Employee Employee { get; set; }
        public virtual Store Store { get; set; }
    }
}
