//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RingCentralDataIntegration
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Employee()
        {
            this.EmployeeAdjustments = new HashSet<EmployeeAdjustment>();
            this.EmployeeCharacteristics = new HashSet<EmployeeCharacteristic>();
            this.EmployeeStatusHistories = new HashSet<EmployeeStatusHistory>();
            this.EmployeeTimeDetails = new HashSet<EmployeeTimeDetail>();
            this.InvoiceActivities = new HashSet<InvoiceActivity>();
            this.InvoiceAdjustments = new HashSet<InvoiceAdjustment>();
            this.StoreHierarchies = new HashSet<StoreHierarchy>();
        }
    
        public int EmployeeID { get; set; }
        public int PosID { get; set; }
        public string EmployeeName { get; set; }
        public Nullable<int> PrimaryStoreID { get; set; }
        public int DivisionID { get; set; }
        public int EmployeeStatusID { get; set; }
        public Nullable<int> OriginID { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
    
        public virtual Division Division { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EmployeeAdjustment> EmployeeAdjustments { get; set; }
        public virtual EmployeeStatu EmployeeStatu { get; set; }
        public virtual Origin Origin { get; set; }
        public virtual Store Store { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EmployeeCharacteristic> EmployeeCharacteristics { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EmployeeStatusHistory> EmployeeStatusHistories { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EmployeeTimeDetail> EmployeeTimeDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InvoiceActivity> InvoiceActivities { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InvoiceAdjustment> InvoiceAdjustments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StoreHierarchy> StoreHierarchies { get; set; }
    }
}
