//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RingCentralDataIntegration
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmployeeSalesKPI
    {
        public int EmployeeID { get; set; }
        public int StoreID { get; set; }
        public int DivisionID { get; set; }
        public string EmployeeStatus { get; set; }
        public System.DateTime ActivityDate { get; set; }
        public Nullable<decimal> GrossProfit { get; set; }
        public Nullable<int> Opps { get; set; }
        public Nullable<int> GrossAdds { get; set; }
        public Nullable<int> Upgrades { get; set; }
        public Nullable<int> StrategicProducts { get; set; }
        public Nullable<int> DLife { get; set; }
        public Nullable<int> AdvancedTV { get; set; }
        public Nullable<int> CRU { get; set; }
        public Nullable<int> GoPhone { get; set; }
        public Nullable<decimal> AccessoryGP { get; set; }
        public Nullable<int> PostPaidGrossAdds { get; set; }
        public Nullable<int> Wired { get; set; }
    }
}
