//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RingCentralDataIntegration
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmployeeTimeDetail
    {
        public int EmployeeTimeDetailID { get; set; }
        public int EmployeeID { get; set; }
        public int StoreID { get; set; }
        public System.DateTime ClockIn { get; set; }
        public System.DateTime ClockOut { get; set; }
    
        public virtual Employee Employee { get; set; }
        public virtual Store Store { get; set; }
    }
}
