//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RingCentralDataIntegration
{
    using System;
    using System.Collections.Generic;
    
    public partial class EntityHistory
    {
        public long EntityHistoryID { get; set; }
        public int EntityID { get; set; }
        public int DivisionID { get; set; }
        public int CollectionID { get; set; }
        public Nullable<int> ElementID { get; set; }
        public Nullable<int> DefinitionID { get; set; }
        public Nullable<int> StatusID { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public bool IsDeleted { get; set; }
        public System.DateTime CreateDate { get; set; }
    
        public virtual Collection Collection { get; set; }
        public virtual Definition Definition { get; set; }
        public virtual Element Element { get; set; }
    }
}
