//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RingCentralDataIntegration
{
    using System;
    using System.Collections.Generic;
    
    public partial class GoalsByDay
    {
        public int GoalID { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<double> DailyGoal { get; set; }
        public double MonthlyGoal { get; set; }
        public string GoalType { get; set; }
        public string GoalDescription { get; set; }
        public Nullable<double> GoalWeight { get; set; }
        public string WeightType { get; set; }
        public int StoreID { get; set; }
    }
}
