//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RingCentralDataIntegration
{
    using System;
    using System.Collections.Generic;
    
    public partial class Goal
    {
        public int GoalID { get; set; }
        public int GoalDescriptionID { get; set; }
        public System.DateTime GoalDate { get; set; }
        public int StoreID { get; set; }
        public double Goal1 { get; set; }
        public Nullable<int> GoalWeightID { get; set; }
    
        public virtual GoalDescription GoalDescription { get; set; }
        public virtual GoalWeight GoalWeight { get; set; }
        public virtual Store Store { get; set; }
    }
}
