//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RingCentralDataIntegration
{
    using System;
    using System.Collections.Generic;
    
    public partial class Inventory
    {
        public int InventoryID { get; set; }
        public int SkuID { get; set; }
        public int StoreID { get; set; }
        public int InventoryDate { get; set; }
        public Nullable<int> VendorID { get; set; }
        public Nullable<int> SerialNumberID { get; set; }
        public Nullable<int> VendorPNID { get; set; }
        public Nullable<int> ManufacturerPNID { get; set; }
        public Nullable<int> BarcodeID { get; set; }
        public int Quantity { get; set; }
        public decimal CostPerUnit { get; set; }
        public int StatusID { get; set; }
    
        public virtual InventoryIdentificationCode InventoryIdentificationCode { get; set; }
        public virtual InventoryIdentificationCode InventoryIdentificationCode1 { get; set; }
        public virtual InventoryIdentificationCode InventoryIdentificationCode2 { get; set; }
        public virtual InventoryIdentificationCode InventoryIdentificationCode3 { get; set; }
        public virtual Sku Sku { get; set; }
        public virtual Status Status { get; set; }
        public virtual Store Store { get; set; }
        public virtual Vendor Vendor { get; set; }
    }
}
