//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RingCentralDataIntegration
{
    using System;
    using System.Collections.Generic;
    
    public partial class InvoiceAdjustment
    {
        public int InvoiceAdjustmentID { get; set; }
        public int InvoiceID { get; set; }
        public int EmployeeID { get; set; }
        public System.DateTime AdjustmentDate { get; set; }
    
        public virtual Employee Employee { get; set; }
        public virtual Invoice Invoice { get; set; }
    }
}
