//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RingCentralDataIntegration
{
    using System;
    using System.Collections.Generic;
    
    public partial class InvoiceActivity
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public InvoiceActivity()
        {
            this.LineItems = new HashSet<LineItem>();
        }
    
        public int InvoiceActivityID { get; set; }
        public int InvoiceID { get; set; }
        public int EmployeeID { get; set; }
        public int StoreID { get; set; }
        public System.DateTime ActivityDateTime { get; set; }
    
        public virtual Employee Employee { get; set; }
        public virtual Invoice Invoice { get; set; }
        public virtual Store Store { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LineItem> LineItems { get; set; }
    }
}
