//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RingCentralDataIntegration
{
    using System;
    using System.Collections.Generic;
    
    public partial class LineItem
    {
        public int LineItemID { get; set; }
        public int InvoiceActivityID { get; set; }
        public int LineItemOrder { get; set; }
        public int LineReferenceID { get; set; }
        public int LineItemTypeID { get; set; }
        public int SkuID { get; set; }
        public decimal Price { get; set; }
        public decimal Cost { get; set; }
        public decimal Profit { get; set; }
        public int Quantity { get; set; }
    
        public virtual InvoiceActivity InvoiceActivity { get; set; }
        public virtual LineItemType LineItemType { get; set; }
        public virtual Sku Sku { get; set; }
    }
}
