//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RingCentralDataIntegration
{
    using System;
    using System.Collections.Generic;
    
    public partial class Metric
    {
        public int MetricID { get; set; }
        public int DealerCodeID { get; set; }
        public int MetricDescriptionID { get; set; }
        public System.DateTime Date { get; set; }
        public double MetricValue { get; set; }
        public int IntervalID { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
    
        public virtual DealerCode DealerCode { get; set; }
        public virtual Interval Interval { get; set; }
        public virtual MetricDescription MetricDescription { get; set; }
    }
}
