//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RingCentralDataIntegration
{
    using System;
    using System.Collections.Generic;
    
    public partial class RelationshipDefinition
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public RelationshipDefinition()
        {
            this.EntityRelationshipHistories = new HashSet<EntityRelationshipHistory>();
            this.EntityRelationships = new HashSet<EntityRelationship>();
        }
    
        public int RelationshipDefinitionID { get; set; }
        public string RelationshipDefinition1 { get; set; }
        public int ParentCollectionID { get; set; }
        public int ChildCollectionID { get; set; }
        public bool AllowMultipleParents { get; set; }
        public System.DateTime CreateDate { get; set; }
        public System.DateTime UpdateDate { get; set; }
    
        public virtual Collection Collection { get; set; }
        public virtual Collection Collection1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EntityRelationshipHistory> EntityRelationshipHistories { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EntityRelationship> EntityRelationships { get; set; }
    }
}
