//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RingCentralDataIntegration
{
    using System;
    using System.Collections.Generic;
    
    public partial class RQLocation
    {
        public string StoreID { get; set; }
        public string StoreName { get; set; }
        public string Disabled { get; set; }
        public string Abbreviation { get; set; }
        public string ManagerEmployeeID { get; set; }
        public string ManagerCommissionable { get; set; }
        public string Address { get; set; }
        public string City { get; set; }
        public string StateProv { get; set; }
        public string ZipPostal { get; set; }
        public string Country { get; set; }
        public string PhoneNumber { get; set; }
        public string FaxNumber { get; set; }
        public string DistrictName { get; set; }
        public string RegionName { get; set; }
        public string ChannelName { get; set; }
        public string StoreType { get; set; }
        public string GLCode { get; set; }
        public string SquareFootage { get; set; }
        public string LocationCode { get; set; }
        public string Latitude { get; set; }
        public string Longitude { get; set; }
        public string AddressVerified { get; set; }
        public string TimeZone { get; set; }
        public string AdjustDST { get; set; }
        public string CashPolicy { get; set; }
        public string MaxCashDrawer { get; set; }
        public string Serial_on_OE { get; set; }
        public string Phone_on_OE { get; set; }
        public string PAW_on_OE { get; set; }
        public string Comment_on_OE { get; set; }
        public string HideCustomerAddress { get; set; }
        public string EmailAddress { get; set; }
        public string GeneralLocationNotes { get; set; }
        public string SaleInvoiceComment { get; set; }
        public string BankDetails { get; set; }
        public string Taxes { get; set; }
        public string Rent { get; set; }
        public string PropertyTaxes { get; set; }
        public string InsuranceAmount { get; set; }
        public string OtherCharges { get; set; }
        public string DepositTaken { get; set; }
        public string LeaseNotes { get; set; }
        public string InsuranceCompany { get; set; }
        public string LandlordNotes { get; set; }
        public string LandlordName { get; set; }
        public string UseLocationEmail { get; set; }
        public string LocationEntityID { get; set; }
        public System.DateTime AccessedDate { get; set; }
        public Nullable<int> DivisionID { get; set; }
        public Nullable<System.DateTime> LeaseStartDate { get; set; }
        public Nullable<System.DateTime> LeaseEndDate { get; set; }
    }
}
