//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RingCentralDataIntegration
{
    using System;
    using System.Collections.Generic;
    
    public partial class RQRequestType
    {
        public Nullable<int> RequestTypeID { get; set; }
        public string RequestTypeDescription { get; set; }
        public string Message { get; set; }
        public System.DateTime AccessedDate { get; set; }
    }
}
