//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RingCentralDataIntegration
{
    using System;
    using System.Collections.Generic;
    
    public partial class RQSalesDetail
    {
        public string ChannelName { get; set; }
        public int StoreID { get; set; }
        public string StoreName { get; set; }
        public Nullable<int> CustomerID { get; set; }
        public string CustomerName { get; set; }
        public int EmployeeID { get; set; }
        public System.DateTime DateCreated { get; set; }
        public string InvoiceNumber { get; set; }
        public Nullable<long> LineID { get; set; }
        public string ProductSKU { get; set; }
        public Nullable<decimal> Price { get; set; }
        public Nullable<decimal> Cost { get; set; }
        public Nullable<int> RQPriority { get; set; }
        public int Quantity { get; set; }
        public string EmployeeName { get; set; }
        public Nullable<int> DivisionID { get; set; }
    }
}
