//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RingCentralDataIntegration
{
    using System;
    using System.Collections.Generic;
    
    public partial class SalesKPI
    {
        public int StoreID { get; set; }
        public int DivisionID { get; set; }
        public System.DateTime ActivityDate { get; set; }
        public Nullable<decimal> GrossProfit { get; set; }
        public Nullable<int> Opps { get; set; }
        public Nullable<int> GrossAdds { get; set; }
        public Nullable<int> Upgrades { get; set; }
        public Nullable<int> StrategicProducts { get; set; }
        public Nullable<int> DLife { get; set; }
        public Nullable<int> AdvancedTV { get; set; }
        public Nullable<int> CRU { get; set; }
        public Nullable<int> GoPhone { get; set; }
        public Nullable<decimal> AccessoryGP { get; set; }
        public Nullable<int> PostPaidGrossAdds { get; set; }
        public Nullable<int> Wired { get; set; }
        public Nullable<int> Traffic { get; set; }
        public Nullable<int> Wearables { get; set; }
        public Nullable<int> UverseUnits { get; set; }
        public Nullable<int> TotalPhones { get; set; }
        public Nullable<int> TabletUnits { get; set; }
        public Nullable<int> TabletData { get; set; }
        public Nullable<int> Smartphones { get; set; }
        public Nullable<int> FeatUnits { get; set; }
        public Nullable<decimal> RevenueNoCoupons { get; set; }
        public Nullable<int> NonContract { get; set; }
        public Nullable<int> Next { get; set; }
        public Nullable<int> LG_G5 { get; set; }
        public Nullable<int> iOS { get; set; }
        public Nullable<int> IntegratedProducts { get; set; }
        public Nullable<int> HYLA { get; set; }
        public Nullable<decimal> GadgetGuardGP { get; set; }
        public Nullable<decimal> FeatureGP { get; set; }
        public Nullable<int> DirecTVUnits { get; set; }
        public Nullable<int> BYOD { get; set; }
        public Nullable<int> AndroidUnits { get; set; }
        public Nullable<decimal> AllCoupons { get; set; }
        public Nullable<int> AccessoryUnits { get; set; }
        public Nullable<int> AccEligOpps { get; set; }
        public Nullable<decimal> AccessoryCoupons { get; set; }
        public Nullable<decimal> RawGrossProfit { get; set; }
        public Nullable<int> NoniOSSmartPhones { get; set; }
        public Nullable<int> HSI { get; set; }
        public Nullable<int> MobileInsurance { get; set; }
    }
}
