//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RingCentralDataIntegration
{
    using System;
    using System.Collections.Generic;
    
    public partial class SalesCouponDetail
    {
        public long InvoiceReferenceID { get; set; }
        public System.DateTime ActivityDateTime { get; set; }
        public int SkuID { get; set; }
        public decimal Profit { get; set; }
        public int Quantity { get; set; }
        public decimal Revenue { get; set; }
    }
}
