//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RingCentralDataIntegration
{
    using System;
    using System.Collections.Generic;
    
    public partial class SalesDetail
    {
        public int InvoiceID { get; set; }
        public int DivisionID { get; set; }
        public string InvoiceNumber { get; set; }
        public int InvoiceActivityID { get; set; }
        public Nullable<long> InvoiceReferenceID { get; set; }
        public System.DateTime ActivityDateTime { get; set; }
        public System.DateTime InvoiceDate { get; set; }
        public int EmployeeID { get; set; }
        public int StoreID { get; set; }
        public Nullable<int> SkuID { get; set; }
        public decimal Profit { get; set; }
        public Nullable<int> Quantity { get; set; }
        public decimal Revenue { get; set; }
        public Nullable<int> CustomerID { get; set; }
        public Nullable<int> ReferenceSkuID { get; set; }
    }
}
