//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RingCentralDataIntegration
{
    using System;
    using System.Collections.Generic;
    
    public partial class SisenseInvoiceFlag
    {
        public int DivisionID { get; set; }
        public string InvoiceNumber { get; set; }
        public Nullable<int> SMServiceFlag { get; set; }
        public Nullable<int> smMobilityiPadFlag { get; set; }
        public Nullable<int> smMobilityiPhoneFlag { get; set; }
    }
}
