//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RingCentralDataIntegration
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sku
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Sku()
        {
            this.Inventories = new HashSet<Inventory>();
            this.LineItems = new HashSet<LineItem>();
        }
    
        public int SkuID { get; set; }
        public string Sku1 { get; set; }
        public Nullable<long> ParentProductID { get; set; }
        public string ProductDescription { get; set; }
        public Nullable<bool> ProductEnabled { get; set; }
        public string Manufacturer { get; set; }
        public string LevelOne { get; set; }
        public string LevelTwo { get; set; }
        public string LevelThree { get; set; }
        public string LevelFour { get; set; }
        public string LevelFive { get; set; }
        public string LevelSix { get; set; }
        public string LevelSeven { get; set; }
        public string LevelEight { get; set; }
        public int DivisionID { get; set; }
    
        public virtual Division Division { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Inventory> Inventories { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LineItem> LineItems { get; set; }
    }
}
