//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RingCentralDataIntegration
{
    using System;
    using System.Collections.Generic;
    
    public partial class Skus1
    {
        public int SkuID { get; set; }
        public string Sku { get; set; }
        public Nullable<long> ParentProductID { get; set; }
        public string ProductDescription { get; set; }
        public Nullable<bool> ProductEnabled { get; set; }
        public string Manufacturer { get; set; }
        public string LevelOne { get; set; }
        public string LevelTwo { get; set; }
        public string LevelThree { get; set; }
        public string LevelFour { get; set; }
        public string LevelFive { get; set; }
        public string LevelSix { get; set; }
        public string LevelSeven { get; set; }
        public string LevelEight { get; set; }
        public int DivisionID { get; set; }
    }
}
