//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RingCentralDataIntegration
{
    using System;
    using System.Collections.Generic;
    
    public partial class StatusProcess
    {
        public int StatusProcessID { get; set; }
        public int ProcessID { get; set; }
        public int StatusID { get; set; }
    
        public virtual Process Process { get; set; }
        public virtual Status Status { get; set; }
    }
}
