//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RingCentralDataIntegration
{
    using System;
    using System.Collections.Generic;
    
    public partial class StoreHierarchy
    {
        public int StoreHierarchyID { get; set; }
        public int StoreID { get; set; }
        public int HierarchyNameID { get; set; }
        public int HierarchyLevelID { get; set; }
        public Nullable<int> HierarchyParentNameID { get; set; }
        public System.DateTime HierarchyDate { get; set; }
        public Nullable<int> ManagerID { get; set; }
    
        public virtual Employee Employee { get; set; }
        public virtual HierarchyLevel HierarchyLevel { get; set; }
        public virtual HierarchyName HierarchyName { get; set; }
        public virtual Store Store { get; set; }
    }
}
