//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RingCentralDataIntegration
{
    using System;
    using System.Collections.Generic;
    
    public partial class Stores1
    {
        public int StoreID { get; set; }
        public int DivisionID { get; set; }
        public string Store { get; set; }
        public int StoreNumber { get; set; }
        public string StoreName { get; set; }
        public string Address { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public string Zip { get; set; }
        public string Timezone { get; set; }
        public Nullable<decimal> Latitude { get; set; }
        public Nullable<decimal> Longitude { get; set; }
        public string Backdoor { get; set; }
        public string Billpay { get; set; }
        public Nullable<System.DateTime> ClosedDate { get; set; }
        public Nullable<bool> DigitalLife { get; set; }
        public string StoreType { get; set; }
        public Nullable<System.DateTime> OpenDate { get; set; }
        public Nullable<bool> OpenSunday { get; set; }
        public string Tier { get; set; }
        public Nullable<bool> Uverse { get; set; }
        public Nullable<bool> Wired { get; set; }
        public string District { get; set; }
        public string Region { get; set; }
        public string Market { get; set; }
        public string Origin { get; set; }
        public string StoreStatus { get; set; }
    }
}
