//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RingCentralDataIntegration
{
    using System;
    using System.Collections.Generic;
    
    public partial class StoreAdjustment
    {
        public int StoreAdjustmentID { get; set; }
        public int StoreID { get; set; }
        public System.DateTime StartDate { get; set; }
        public System.DateTime EndDate { get; set; }
        public int AdjustmentDescriptionID { get; set; }
        public int AdjustmentTypeID { get; set; }
    
        public virtual AdjustmentDescription AdjustmentDescription { get; set; }
        public virtual AdjustmentType AdjustmentType { get; set; }
        public virtual Store Store { get; set; }
    }
}
