//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RingCentralDataIntegration
{
    using System;
    using System.Collections.Generic;
    
    public partial class StoreHistory
    {
        public int StoreHistoryID { get; set; }
        public int StoreID { get; set; }
        public Nullable<int> LocationID { get; set; }
        public int OriginID { get; set; }
        public int StoreStatusID { get; set; }
        public int HistoryOrder { get; set; }
        public int HistoryTypeID { get; set; }
        public System.DateTime CreateDate { get; set; }
    
        public virtual HistoryType HistoryType { get; set; }
    }
}
