//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RingCentralDataIntegration
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class TechBrandsContext : DbContext
    {
        public TechBrandsContext()
            : base("name=TechBrandsContext")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AdjustmentDescription> AdjustmentDescriptions { get; set; }
        public virtual DbSet<AdjustmentType> AdjustmentTypes { get; set; }
        public virtual DbSet<Alias> Aliases { get; set; }
        public virtual DbSet<AliasType> AliasTypes { get; set; }
        public virtual DbSet<Calendar> Calendars { get; set; }
        public virtual DbSet<CalendarType> CalendarTypes { get; set; }
        public virtual DbSet<Collection> Collections { get; set; }
        public virtual DbSet<CustomerAddress> CustomerAddresses { get; set; }
        public virtual DbSet<CustomerContact> CustomerContacts { get; set; }
        public virtual DbSet<Customer> Customers { get; set; }
        public virtual DbSet<CustomerTimeline> CustomerTimelines { get; set; }
        public virtual DbSet<DataType> DataTypes { get; set; }
        public virtual DbSet<DealerCodeCharacteristic> DealerCodeCharacteristics { get; set; }
        public virtual DbSet<DealerCodeCharacteristicType> DealerCodeCharacteristicTypes { get; set; }
        public virtual DbSet<DealerCode> DealerCodes { get; set; }
        public virtual DbSet<DealerCodeStatu> DealerCodeStatus { get; set; }
        public virtual DbSet<DealerCodeType> DealerCodeTypes { get; set; }
        public virtual DbSet<DealerHierarchy> DealerHierarchies { get; set; }
        public virtual DbSet<DealerHierarchyLevel> DealerHierarchyLevels { get; set; }
        public virtual DbSet<DealerHierarchyName> DealerHierarchyNames { get; set; }
        public virtual DbSet<DefinitionHierarchy> DefinitionHierarchies { get; set; }
        public virtual DbSet<Definition> Definitions { get; set; }
        public virtual DbSet<DivisionAdjustment> DivisionAdjustments { get; set; }
        public virtual DbSet<Division> Divisions { get; set; }
        public virtual DbSet<Element> Elements { get; set; }
        public virtual DbSet<EmployeeAdjustment> EmployeeAdjustments { get; set; }
        public virtual DbSet<Employee> Employees { get; set; }
        public virtual DbSet<EmployeeStatu> EmployeeStatus { get; set; }
        public virtual DbSet<EmployeeStatusHistory> EmployeeStatusHistories { get; set; }
        public virtual DbSet<EmployeeTimeDetail> EmployeeTimeDetails { get; set; }
        public virtual DbSet<Entity> Entities { get; set; }
        public virtual DbSet<EntityElement> EntityElements { get; set; }
        public virtual DbSet<EntityHistory> EntityHistories { get; set; }
        public virtual DbSet<EntityRelationshipHistory> EntityRelationshipHistories { get; set; }
        public virtual DbSet<EntityRelationship> EntityRelationships { get; set; }
        public virtual DbSet<GoalDescription> GoalDescriptions { get; set; }
        public virtual DbSet<Goal> Goals { get; set; }
        public virtual DbSet<GoalWeight> GoalWeights { get; set; }
        public virtual DbSet<HierarchyLevel> HierarchyLevels { get; set; }
        public virtual DbSet<HierarchyName> HierarchyNames { get; set; }
        public virtual DbSet<HistoryType> HistoryTypes { get; set; }
        public virtual DbSet<Interval> Intervals { get; set; }
        public virtual DbSet<Inventory> Inventories { get; set; }
        public virtual DbSet<InventoryIdentificationCode> InventoryIdentificationCodes { get; set; }
        public virtual DbSet<InvoiceActivity> InvoiceActivities { get; set; }
        public virtual DbSet<InvoiceAdjustment> InvoiceAdjustments { get; set; }
        public virtual DbSet<Invoice> Invoices { get; set; }
        public virtual DbSet<LineItem> LineItems { get; set; }
        public virtual DbSet<LineItemType> LineItemTypes { get; set; }
        public virtual DbSet<Location> Locations { get; set; }
        public virtual DbSet<MetricDescription> MetricDescriptions { get; set; }
        public virtual DbSet<Metric> Metrics { get; set; }
        public virtual DbSet<Origin> Origins { get; set; }
        public virtual DbSet<Process> Processes { get; set; }
        public virtual DbSet<RelationshipDefinition> RelationshipDefinitions { get; set; }
        public virtual DbSet<Sku> Skus { get; set; }
        public virtual DbSet<Status> Status { get; set; }
        public virtual DbSet<StatusProcess> StatusProcesses { get; set; }
        public virtual DbSet<StatusStatusType> StatusStatusTypes { get; set; }
        public virtual DbSet<StatusType> StatusTypes { get; set; }
        public virtual DbSet<StoreAdjustment> StoreAdjustments { get; set; }
        public virtual DbSet<StoreCharacteristic> StoreCharacteristics { get; set; }
        public virtual DbSet<StoreCharacteristicType> StoreCharacteristicTypes { get; set; }
        public virtual DbSet<StoreHierarchy> StoreHierarchies { get; set; }
        public virtual DbSet<StoreHistory> StoreHistories { get; set; }
        public virtual DbSet<Store> Stores { get; set; }
        public virtual DbSet<StoreStatu> StoreStatus { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<TrafficDetail> TrafficDetails { get; set; }
        public virtual DbSet<Vendor> Vendors { get; set; }
        public virtual DbSet<WeightType> WeightTypes { get; set; }
        public virtual DbSet<Traffic> Traffic { get; set; }
        public virtual DbSet<AccountLevel> AccountLevels { get; set; }
        public virtual DbSet<CostCenter> CostCenters { get; set; }
        public virtual DbSet<FTE> FTEs { get; set; }
        public virtual DbSet<GLAccountDetail> GLAccountDetails { get; set; }
        public virtual DbSet<GLAccountType> GLAccountTypes { get; set; }
        public virtual DbSet<TBAccount> TBAccounts { get; set; }
        public virtual DbSet<EmployeeCharacteristic> EmployeeCharacteristics { get; set; }
        public virtual DbSet<EmployeeCharacteristicType> EmployeeCharacteristicTypes { get; set; }
        public virtual DbSet<AddressAbbr> AddressAbbrs { get; set; }
        public virtual DbSet<CarrierDealerCode> CarrierDealerCodes { get; set; }
        public virtual DbSet<CarrierMetric> CarrierMetrics { get; set; }
        public virtual DbSet<DailyPayByStore> DailyPayByStores { get; set; }
        public virtual DbSet<Employees1> Employees1 { get; set; }
        public virtual DbSet<EmployeeSalesKPI> EmployeeSalesKPIs { get; set; }
        public virtual DbSet<EmployeeSalesKPIs2> EmployeeSalesKPIs2 { get; set; }
        public virtual DbSet<GoalsByDay> GoalsByDays { get; set; }
        public virtual DbSet<SalesCouponDetail> SalesCouponDetails { get; set; }
        public virtual DbSet<SalesDetail> SalesDetails { get; set; }
        public virtual DbSet<SalesKPI> SalesKPIs { get; set; }
        public virtual DbSet<SisenseInvoiceFlag> SisenseInvoiceFlags { get; set; }
        public virtual DbSet<Skus1> Skus1 { get; set; }
        public virtual DbSet<Stores1> Stores1 { get; set; }
        public virtual DbSet<StoreSalesKPI> StoreSalesKPIs { get; set; }
        public virtual DbSet<RQCardType> RQCardTypes { get; set; }
        public virtual DbSet<RQEntryType> RQEntryTypes { get; set; }
        public virtual DbSet<RQLocation> RQLocations { get; set; }
        public virtual DbSet<RQRequestType> RQRequestTypes { get; set; }
        public virtual DbSet<RQSalesDetail> RQSalesDetails { get; set; }
    }
}
