//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RingCentralDataIntegration
{
    using System;
    using System.Collections.Generic;
    
    public partial class Traffic
    {
        public int TrafficID { get; set; }
        public int StoreID { get; set; }
        public System.DateTime TrafficDate { get; set; }
        public int TrafficCount { get; set; }
        public string TrafficType { get; set; }
    
        public virtual Store Store { get; set; }
    }
}
